# Generated by Django 6.0.1 on 2026-01-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='aqe',
            new_name='age',
        ),
    ]
